# Generated by Django 2.1.4 on 2019-01-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogspost_keyword1'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.AlterField(
            model_name='blogspost',
            name='timestamp',
            field=models.DateTimeField(verbose_name='保存日期'),
        ),
    ]
